name: AWS CDK CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.ts"
      - "src/**"
      - ".github/workflows/cdk.yml"
      - "**.json"
      - "**.yaml"

env:
  GITHUB_OAUTH_TOKEN: ${{ secrets.ACCESS_TOKEN_GITHUB }}
  WEBSITE_DEV_PASS: ${{ secrets.WEBSITE_DEV_PASS }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  COGNITO_AFFILIATE_REGION: ${{ secrets.COGNITO_AFFILIATE_REGION }}
  GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
  GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_API_SERVICE_ACCOUNT_INFO: ${{ secrets.GOOGLE_API_SERVICE_ACCOUNT_INFO }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
  SLACK_WORKSPACE_ID: ${{ secrets.SLACK_WORKSPACE_ID }}
  BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DEPLOY_KEY: ${{ secrets.FEEDS_DEPLOY_PRIVATE_KEY }}
  STAGE: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm run build

  verify:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Setup CDK
        run: |
          pnpm install -g aws-cdk
          pnpm install
      - name: Diagnose
        run: pnpm run cdk doctor

      - name: Diff
        id: diff
        run: cdk diff
